name       : links
version    : 2.18
release    : 6
source     :
    - http://links.twibright.com/download/links-2.18.tar.gz : ad33d0abfec9627a5ddc34740ec69f1dbec457528581bf23fee4fdcaa90f2332
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
