name       : links
version    : 2.13
release    : 2
source     :
    - http://links.twibright.com/download/links-2.13.tar.gz : bcd068b5b47f604f91091c541d469df2afb6bd6604cddd6f059a17ec9ceb74ae
license    : GPL-2.0
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
