name       : links
version    : '2.27'
release    : 23
source     :
    - http://links.twibright.com/download/links-2.27.tar.bz2 : d8ddcbfcede7cdde80abeb0a236358f57fa6beb2bcf92e109624e9b896f9ebb4
homepage   : http://links.twibright.com/
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser, similar to Lynx
description: |
    Links is a web browser running in both graphics and text mode, similar to Lynx.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libzstd)
    - pkgconfig(xt)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure --enable-graphics
build      : |
    %make
install    : |
    %make_install
