name       : links
version    : '2.24'
release    : 17
source     :
    - http://links.twibright.com/download/links-2.24.tar.bz2 : 9b12f5ba2d068306d7ff7385b520cdcafdc0e55c87eec877abb0e78288525430
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libzstd)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
