name       : links
version    : '2.19'
release    : 7
source     :
    - http://links.twibright.com/download/links-2.19.tar.gz : 37299f804f22c945bf63e22a7bc4418bbb8144b410c0ced70b82ebe6f9e3c82b
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
