name       : links
version    : '2.25'
release    : 20
source     :
    - http://links.twibright.com/download/links-2.25.tar.bz2 : 2dd78508698e8279ef4f09a3a2a21e9595040113402da6c553974414fb49dd2c
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libzstd)
    - pkgconfig(xt)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure --enable-graphics
build      : |
    %make
install    : |
    %make_install
