name       : links
version    : 2.17
release    : 5
source     :
    - http://links.twibright.com/download/links-2.17.tar.gz : 180ef70c60129b5a591a39a3ea33920ba7d181a83109cb75b1772e54cd37ebbc
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
