name       : links
version    : '2.28'
release    : 24
source     :
    - http://links.twibright.com/download/links-2.28.tar.bz2 : 2fd5499b13dee59457c132c167b8495c40deda75389489c6cccb683193f454b4
homepage   : http://links.twibright.com/
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser, similar to Lynx
description: |
    Links is a web browser running in both graphics and text mode, similar to Lynx.
builddeps  :
    - pkgconfig(bzip2) 
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libzstd)
    - pkgconfig(xt)
    - gpm-devel
setup      : |
    %configure --enable-graphics
build      : |
    %make
install    : |
    %make_install
