name       : links
version    : '2.22'
release    : 14
source     :
    - http://links.twibright.com/download/links-2.22.tar.bz2 : 0364986b3a7f1e8e3171bea362b53f71e1dd3360a8842d66fdc65580ebc2084d
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libzstd)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
