name       : links
version    : 2.12
release    : 1
source     :
    - http://links.twibright.com/download/links-2.12.tar.gz : 2e3da6193de9d6ee71bc4beab17169ecc58d7cbf2e20192a3f518ed9f7f22e33
license    : GPL
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
