name       : links
version    : 2.16
release    : 4
source     :
    - http://links.twibright.com/download/links-2.16.tar.gz : 83ab4557d9b121570384d1bd27adf16f962b9b007bac5780ae094e6fff6b3d62
license    : GPL-2.0-only
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
