name       : links
version    : 2.15
release    : 3
source     :
    - http://links.twibright.com/download/links-2.15.tar.gz : 677f594b58dc532e63913cd61b85cc1aa6f0385e333b88766eb3415b41b3a375
license    : GPL-2.0-only
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
