name       : links
version    : '2.26'
release    : 21
source     :
    - http://links.twibright.com/download/links-2.26.tar.bz2 : f05b3577f25dbe63e491c424f0ecb31f7bfadce9b2bc2f111dfed049c004c9cb
homepage   : http://links.twibright.com/
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser, similar to Lynx
description: |
    Links is a web browser running in both graphics and text mode, similar to Lynx.
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libzstd)
    - pkgconfig(xt)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure --enable-graphics
build      : |
    %make
install    : |
    %make_install
