name       : links
version    : '2.23'
release    : 16
source     :
    - http://links.twibright.com/download/links-2.23.tar.bz2 : 6660d202f521fd18bf5184c3f1732d1fa7426a103374277ad1cdb8e57ce6ac45
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libzstd)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
