name       : links
version    : 2.20.1
release    : 9
source     :
    - http://links.twibright.com/download/links-2.20.1.tar.bz2 : bb28a72cb72ca275742ef79e92ba468f0707863366bff2704b0ff6ce52790405
license    : GPL-2.0-or-later
component  : network.web.browser
summary    : A text WWW browser
description: |
    A text WWW browser, similar to Lynx
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libzstd)
    - bzip2-devel
    - gpm-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
